spring.application.name=Integrador-SinTeclados

# Configuración del DataSource (Conexión a PostgreSQL en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/sinTecladosDB
spring.datasource.username=sinTeclados
spring.datasource.password=sinTeclados
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Configuración de H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Configuración del DataSource (Fuente de Datos)
#spring.datasource.url=jdbc:h2:mem:proyectodb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Configuración de JPA (Hibernate)
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'update': Intenta crear/actualizar las tablas basado en tus clases Java
#spring.jpa.hibernate.ddl-auto=update
# Muestra el SQL que se está ejecutando en la consola
#spring.jpa.show-sql=true